/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestionrecursoshumanos.Vista;

import gestionrecursoshumanos.Modelo.Contrato;
import gestionrecursoshumanos.Modelo.ContratoDao;
import gestionrecursoshumanos.Modelo.Personas;
import gestionrecursoshumanos.Modelo.PersonasDAO;
import gestionrecursoshumanos.Modelo.ProcesoPersona;
import gestionrecursoshumanos.Modelo.ProcesoPersonaDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alejo
 */
public class AdminCont extends javax.swing.JPanel {

    /**
     * Creates new form AdminCak
     */
    public AdminCont() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFEI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        Jfecha = new javax.swing.JComboBox<>();
        Botonllenar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TxtCont = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtFEF = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(1097, 817));
        jPanel2.setMinimumSize(new java.awt.Dimension(1097, 817));

        jLabel3.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FECHA DE FINALIZACION");
        jLabel2.setToolTipText("");

        TxtFEI.setBackground(new java.awt.Color(255, 255, 255));
        TxtFEI.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        TxtFEI.setForeground(new java.awt.Color(0, 0, 0));
        TxtFEI.setText("DD/MM/AAAA");
        TxtFEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFEIActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NUMERO DE CONTRATO");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TIPO DE CONTRATO");
        jLabel5.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONTRATAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID PROCESO DE PERSONA", "CANDIDATO", "SELECCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONTRATACION");

        Jfecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFINIDO", "INDEFINIDO" }));
        Jfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JfechaActionPerformed(evt);
            }
        });

        Botonllenar.setBackground(new java.awt.Color(0, 102, 102));
        Botonllenar.setForeground(new java.awt.Color(255, 255, 255));
        Botonllenar.setText("LLENAR");
        Botonllenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonllenarActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setText("INFO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        TxtCont.setBackground(new java.awt.Color(255, 255, 255));
        TxtCont.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        TxtCont.setForeground(new java.awt.Color(0, 0, 0));
        TxtCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RECHAZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("FECHA DE INICIO");
        jLabel6.setToolTipText("");

        TxtFEF.setBackground(new java.awt.Color(255, 255, 255));
        TxtFEF.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        TxtFEF.setForeground(new java.awt.Color(0, 0, 0));
        TxtFEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFEFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(TxtCont, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton5)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtFEF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtFEI, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Botonllenar)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(616, 616, 616)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(1050, 1050, 1050))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(279, 279, 279)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Botonllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(Jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(726, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFEIActionPerformed

    
    }//GEN-LAST:event_TxtFEIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
    // Obtener el ID de contrato ingresado por el usuario
    String idContratoStr = TxtCont.getText().trim();
    if (idContratoStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un número para el ID del contrato.");
        return;
    }
    int idContrato;
    try {
        idContrato = Integer.parseInt(idContratoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido para el ID del contrato.");
        return;
    }
    System.out.println("ID del contrato: " + idContrato);

    // Obtener el tipo de contrato seleccionado por el usuario del JComboBox
    String tipoContrato = Jfecha.getSelectedItem().toString();
    System.out.println("Tipo de contrato seleccionado: " + tipoContrato);

    // Obtener la fecha de inicio ingresada por el usuario
    String fechaInicioStr = TxtFEI.getText().trim();
    if (fechaInicioStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese la fecha de inicio del contrato.");
        return;
    }
    LocalDate fechaInicio = LocalDate.parse(fechaInicioStr, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
    System.out.println("Fecha de inicio del contrato: " + fechaInicio);

    String fechaFinalizacion;
if (Jfecha.getSelectedItem().toString().equals("INDEFINIDO")) {
    fechaFinalizacion = "INDEFINIDOA";
} else {
    // Obtener la fecha de finalización ingresada por el usuario
    String fechaFinalizacionStr = TxtFEF.getText().trim();
    if (fechaFinalizacionStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese la fecha de finalización del contrato.");
        return;
    }
    // Convertir la fecha de finalización al formato requerido en la base de datos
    LocalDate fechaFinalizacionDate = LocalDate.parse(fechaFinalizacionStr, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
    fechaFinalizacion = fechaFinalizacionDate.toString(); // o puedes formatearla a tu formato preferido
    System.out.println("Fecha de finalización del contrato: " + fechaFinalizacion);
}

    // Obtener el ID del empleado ingresado por el usuario
    String idEmpleadoStr = TxtCont.getText().trim(); // Asumiendo que se ingresa el ID del empleado en el mismo campo que el ID del contrato
    if (idEmpleadoStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un número para el ID del empleado.");
        return;
    }
    int idEmpleado;
    try {
        idEmpleado = Integer.parseInt(idEmpleadoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido para el ID del empleado.");
        return;
    }
    System.out.println("ID del empleado: " + idEmpleado);

    // Verificar si el empleado existe en la base de datos
    ProcesoPersona empleado = new ProcesoPersonaDAO().buscarProcesoPersonaPorId(idEmpleado);
    if (empleado == null) {
        JOptionPane.showMessageDialog(null, "El empleado no fue encontrado en la base de datos.");
        return;
    }

    // Crear el objeto Contrato con los datos obtenidos
    Contrato contrato = new Contrato();
    contrato.setIdContrato(idContrato);
    contrato.setTipoContrato(tipoContrato);
    contrato.setFechaInicio(fechaInicio);
    contrato.setFechaFinalizacion(fechaFinalizacion);
    contrato.setEmpleado(empleado);

    // Insertar el contrato en la base de datos
    new ContratoDao().insert(contrato);

    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(null, "Contrato insertado correctamente.");
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error al insertar el contrato: " + e.getMessage());
}
  
  // Obtener el ID del empleado ingresado por el usuario
String idEmpleadoStr = TxtCont.getText().trim();
int idEmpleado;
try {
    idEmpleado = Integer.parseInt(idEmpleadoStr);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido para el ID del empleado.");
    return;
}

// Verificar si el empleado existe en la base de datos
ProcesoPersona empleado = new ProcesoPersonaDAO().buscarProcesoPersonaPorId(idEmpleado);
if (empleado == null) {
    JOptionPane.showMessageDialog(null, "El empleado no fue encontrado en la base de datos.");
    return;
}

// Llamada al método de actualización de la categoría
 PersonasDAO.actualizarCategoriaPersona(idEmpleado, 2); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonllenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonllenarActionPerformed
      try {
        // Crear instancia de ProcesoPersonaDAO
        ProcesoPersonaDAO procesoPersonaDAO = new ProcesoPersonaDAO();
        // Obtener la lista de todos los procesos de persona
        List<ProcesoPersona> listaProcesoPersona = procesoPersonaDAO.findAll();

        System.out.println("Total de ProcesoPersona en la lista: " + listaProcesoPersona.size());

        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // Limpiar tabla existente
        model.setRowCount(0);

        // Recorrer la lista de ProcesoPersonas y agregar cada procesoPersona como una fila en la tabla
        for (ProcesoPersona procesoPersona : listaProcesoPersona) {
            System.out.println("Agregando ProcesoPersona con ID: " + procesoPersona.getIdProcesoPersona());
            model.addRow(new Object[]{
                procesoPersona.getIdProcesoPersona(),
                procesoPersona.getCandidato().getNombre_Completo(),
                procesoPersona.getSeleccion().getIdProceso()
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage());
    }
      
    }//GEN-LAST:event_BotonllenarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       JOptionPane.showMessageDialog(null, "EL NUMERO DE CONTRATO SEA IGUAL AL DEL PROCESO DE PERSONA PARA UN MEJOR MANEJO DE LOS DATOS");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TxtContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContActionPerformed
        
    }//GEN-LAST:event_TxtContActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtFEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFEFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFEFActionPerformed

    private void JfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JfechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonllenar;
    private javax.swing.JComboBox<String> Jfecha;
    private javax.swing.JTextField TxtCont;
    private javax.swing.JTextField TxtFEF;
    private javax.swing.JTextField TxtFEI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
